# This file was generated by GoReleaser. DO NOT EDIT.
cask "bgrun" do
  version "0.2.2"

  on_linux do
    on_intel do
      sha256 "5e01d3a0bc6457884a4db7443e294afc298caa050d4ecd7b90320454bf1e99cc"
      url "https://github.com/bethropolis/bgrun/releases/download/v#{version}/bgrun_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bethropolis/bgrun"
    end
    on_arm do
      sha256 "8a3027f9ceeed1b7a19a25377e71bfe14a6577dc435721706ed682bf1d48b9b1"
      url "https://github.com/bethropolis/bgrun/releases/download/v#{version}/bgrun_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bethropolis/bgrun"
    end
  end

  name "bgrun"
  desc "Background process manager for development workflows"
  homepage "https://github.com/bethropolis/bgrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bgrun"
  binary "bgrun-daemon"

  # No zap stanza required

end
