# This file was generated by GoReleaser. DO NOT EDIT.
cask "bgrun" do
  version "0.5.0"

  on_linux do
    on_arm do
      sha256 "b4b7538572bd00002d8f69dbe0f1c08684a66e1857bc92f282ca8ec73b5a25da"
      url "https://github.com/bethropolis/bgrun/releases/download/v#{version}/bgrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1332b0e4c565954f45e1c010e6895f91edac28c11dd3a6b0a29448bba93964d8"
      url "https://github.com/bethropolis/bgrun/releases/download/v#{version}/bgrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bgrun"
  desc "Background process manager for development workflows"
  homepage "https://github.com/bethropolis/bgrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bgrun"
  binary "bgrun-daemon"

  # No zap stanza required
end
