# This file was generated by GoReleaser. DO NOT EDIT.
cask "bgrun" do
  version "0.2.1"

  on_linux do
    on_intel do
      sha256 "c20e2bb44cae64846e0d49de22bb828cfc73b2df3105699f569fcadd893e0c88"
      url "https://github.com/bethropolis/bgrun/releases/download/v#{version}/bgrun_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bethropolis/bgrun"
    end
    on_arm do
      sha256 "a9f1d2417bfce87a3670fb64517e3c6ba1062aa0946b08f9856b6f4791efb89f"
      url "https://github.com/bethropolis/bgrun/releases/download/v#{version}/bgrun_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bethropolis/bgrun"
    end
  end

  name "bgrun"
  desc "Background process manager for development workflows"
  homepage "https://github.com/bethropolis/bgrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bgrun"
  binary "bgrun-daemon"

  # No zap stanza required

end
