# This file was generated by GoReleaser. DO NOT EDIT.
cask "kcd" do
  version "1.19.1"

  on_linux do
    on_arm do
      sha256 "2a91fcbb4e72f8b7be7b259aa0205823b68332c6a1bd2dad7b5056e8641beddd"
      url "https://github.com/bethropolis/kcd/releases/download/v#{version}/kcd_#{version}_linux_aarch64.tar.gz"
    end
    on_intel do
      sha256 "b9d953eb07e329ede797031855ea4b5299363aae2e3b3fb8945216e8a27f2fdd"
      url "https://github.com/bethropolis/kcd/releases/download/v#{version}/kcd_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "kcd"
  desc "Lightweight, headless implementation of the KDE Connect protocol (v8) written in Go"
  homepage "https://github.com/bethropolis/kcd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kcd"
  bash_completion "packaging/kcd.bash-completion"
  fish_completion "packaging/kcd.fish-completion"
  zsh_completion "packaging/kcd.zsh-completion"

  # No zap stanza required
end
