# This file was generated by GoReleaser. DO NOT EDIT.
cask "kcd" do
  version "1.16.0"

  on_linux do
    on_intel do
      sha256 "02bd76551ee090eeda290a5fe6d4b81d97488f0c26fa87d3ad0501c6d95e159a"
      url "https://github.com/bethropolis/kcd/releases/download/v#{version}/kcd_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/bethropolis/kcd"
    end
    on_arm do
      sha256 "46a06e0cdfbd3dcf5677a12aca722daf7d0193d5804b985d27b3d5bd5d942881"
      url "https://github.com/bethropolis/kcd/releases/download/v#{version}/kcd_#{version}_linux_aarch64.tar.gz",
        verified: "github.com/bethropolis/kcd"
    end
  end

  name "kcd"
  desc "Lightweight, headless implementation of the KDE Connect protocol (v8) written in Go"
  homepage "https://github.com/bethropolis/kcd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kcd"
  bash_completion "packaging/kcd.bash-completion"
  fish_completion "packaging/kcd.fish-completion"
  zsh_completion "packaging/kcd.zsh-completion"

  # No zap stanza required

end
