# This file was generated by GoReleaser. DO NOT EDIT.
cask "kcd" do
  version "1.22.1"

  on_linux do
    on_arm do
      sha256 "15a872537729965c24a61f09043b4b610f6000be7196970e0fe1f92f9a157e50"
      url "https://github.com/bethropolis/kcd/releases/download/v#{version}/kcd_#{version}_linux_aarch64.tar.gz"
    end
    on_intel do
      sha256 "9cc83b446eadb33bdfa736dad6c55291e90bd1effeb50b8ba575cc5d19938d11"
      url "https://github.com/bethropolis/kcd/releases/download/v#{version}/kcd_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "kcd"
  desc "Lightweight, headless implementation of the KDE Connect protocol (v8) written in Go"
  homepage "https://github.com/bethropolis/kcd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kcd"
  bash_completion "packaging/kcd.bash-completion"
  fish_completion "packaging/kcd.fish-completion"
  zsh_completion "packaging/kcd.zsh-completion"

  # No zap stanza required
end
