# This file was generated by GoReleaser. DO NOT EDIT.
cask "localgo" do
  version "0.6.7"

  on_macos do
    on_arm do
      sha256 "17594693d4caa4c79fb44a68a9a89ad6231dca543b43c2d056aea17b60081833"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f4060d377433bfb9f404642689040c13e68d646f22932ec3f7c979276efe843"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d8128609aa4aaab5c0c54a9766b1aef96634b0fa6ebad7bdf8bdace96259ce83"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "55c50e339b0be8342734ee5741bcbe9498aada54449e83d5283246d8b069df41"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "localgo"
  desc "LocalSend v2 protocol implementation. LAN file transfer CLI"
  homepage "https://github.com/bethropolis/localgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localgo"
  bash_completion "scripts/bash_completion.sh"
  fish_completion "scripts/fish_completion.fish"
  zsh_completion "scripts/zsh_completion.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/localgo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Shell completions are installed automatically.

    To start as a background service:
      localgo serve --quiet --auto-accept
  EOS
end
