# This file was generated by GoReleaser. DO NOT EDIT.
cask "localgo" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "f190091288f40cf02389119135f934c0fa182775e6421c8033aa38c26ebe5db6"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "83e45e53cfb93db28f951fcdaeb558309f393a16e1fee09bd3b188e3286ca518"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "91bd300f706a5c9dd54e972a3a3c85c33bf34d528e27046851eda446b865f1f3"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb51754deb85bf923bc98001844bdd39213fe55edea95afc243096d86ae1e1e6"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "localgo"
  desc "LocalSend v2.1 protocol implementation — LAN file transfer CLI"
  homepage "https://github.com/bethropolis/localgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localgo"
  bash_completion "scripts/bash_completion.sh"
  fish_completion "scripts/fish_completion.fish"
  zsh_completion "scripts/zsh_completion.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/localgo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Shell completions are installed automatically.

    To start as a background service:
      localgo serve --quiet --auto-accept
  EOS
end
