# This file was generated by GoReleaser. DO NOT EDIT.
cask "localgo" do
  version "0.5.10"

  on_macos do
    on_intel do
      sha256 "7056a52485ba3f1e3c013032f6c31c1b96518258c2846d11e4b011bb400eb23e"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d0522798dd2b245be968ec91ca70a49c1a0903c1017cdfafcdc493653d4dafd"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0cf63c97a3f5d819c73993ce2bd4faf8a2808ce92175746813a6ad67213d8f85"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2380fad98d42c9c4d4ef0a2fa0a8d02c6a43da37daaefc61d22c7c8d03fe5ffc"
      url "https://github.com/bethropolis/localgo/releases/download/v#{version}/localgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "localgo"
  desc "LocalSend v2.1 protocol implementation — LAN file transfer CLI"
  homepage "https://github.com/bethropolis/localgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localgo"
  bash_completion "scripts/bash_completion.sh"
  fish_completion "scripts/fish_completion.fish"
  zsh_completion "scripts/zsh_completion.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/localgo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Shell completions are installed automatically.

    To start as a background service:
      localgo serve --quiet --auto-accept
  EOS
end
