# This file was generated by GoReleaser. DO NOT EDIT.
cask "podbox" do
  version "0.3.6"

  on_linux do
    on_intel do
      sha256 "515dacac4b7c860016d5412a3800fa0bdae56458b8550bfa73c08753fc613dea"
      url "https://github.com/bethropolis/podbox/releases/download/v#{version}/podbox-v#{version}-linux-x86_64.tar.gz"
    end
  end

  name "podbox"
  desc "Podman-native container environment manager"
  homepage "https://github.com/bethropolis/podbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podbox"

  # No zap stanza required

  caveats <<~EOS
    Run 'podbox pull' to fetch prebuilt images (the only supported image type).
    Run 'podbox doctor' to verify your setup.
  EOS
end
