# This file was generated by GoReleaser. DO NOT EDIT.
cask "podbox" do
  version "0.4.1"

  on_linux do
    on_intel do
      sha256 "713212139d91dccc09ae9f23095b6e74683b56a8773eb1ebd5af135f3ad77e0f"
      url "https://github.com/bethropolis/podbox/releases/download/v#{version}/podbox-v#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "8da2229025e99d3776d8ead0f425da042cbfbfc4c1a787955eac97b570b4a6e7"
      url "https://github.com/bethropolis/podbox/releases/download/v#{version}/podbox-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "podbox"
  desc "Podman-native container environment manager"
  homepage "https://github.com/bethropolis/podbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podbox"

  # No zap stanza required

  caveats <<~EOS
    Run 'podbox pull' to fetch prebuilt images (the only supported image type).
    Run 'podbox doctor' to verify your setup.
  EOS
end
