# This file was generated by GoReleaser. DO NOT EDIT.
cask "podbox" do
  version "0.3.7"

  on_linux do
    on_intel do
      sha256 "3740a90626459494d89e2c237a8a4259e7d5c2a79ffe24f1b6b45950f64bcae5"
      url "https://github.com/bethropolis/podbox/releases/download/v#{version}/podbox-v#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "48e3ef7ff4674a0e55268e14aa0eb1c758558053a59182659830c4b38393b51d"
      url "https://github.com/bethropolis/podbox/releases/download/v#{version}/podbox-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "podbox"
  desc "Podman-native container environment manager"
  homepage "https://github.com/bethropolis/podbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podbox"

  # No zap stanza required

  caveats <<~EOS
    Run 'podbox pull' to fetch prebuilt images (the only supported image type).
    Run 'podbox doctor' to verify your setup.
  EOS
end
