# This file was generated by GoReleaser. DO NOT EDIT.
cask "sift" do
  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "be87e5ab04235f31c3c729a479dde8ba17f2d384411b1e3f3dbf8a65b5584a3e"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ef79805e2e45b15e3d3053d98f5a2b20d4a76fc737543cf0040e177c6631caf"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f25b5a14cbdc48f69b18ba9a8dbfe1fec67576badc97a947942756e3dc20deb8"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03584c41d7a5fce122ef9b9b61bf124d85b8bab2e9f4e800282717ac5434f8ce"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sift"
  desc "LLM-friendly codebase context picker"
  homepage "https://github.com/bethropolis/sift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sift"

  # No zap stanza required
end
