# This file was generated by GoReleaser. DO NOT EDIT.
cask "sift" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "066ebe350c0823646956dd7eec92961ed8e92eb7cab3334c95b3c5876f1eed0a"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb6cdd3cff15b904f7e79c5518d42effa97aef5a1eba2668b74fcbd4244d873b"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "08719df8efa75935f45d4e563025a71f3eda2e313d490124d48d656c8f8d52b5"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5fe11d1f2f177b11b720365b5993109e5a1542dffeaeb28f03b09e38cdafb21"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sift"
  desc "LLM-friendly codebase context picker"
  homepage "https://github.com/bethropolis/sift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sift"

  # No zap stanza required
end
