# This file was generated by GoReleaser. DO NOT EDIT.
cask "sift" do
  version "1.6.0"

  on_macos do
    on_arm do
      sha256 "f8faaa24188beb284ed2185f7a65613fee54c17436f3206f034771ef51fa3ab6"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e78c1f6895e3c08e258d6a9925635d1b0a01fc0a07f026c6de5e7cb2181d431"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c7d68b6f112d882703f465f4ff6ddedc701c822b5f56b2d619847ea553d5e65"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fbb224e0fdc4684e76ec0cf7f2c42a704ff3c28c97a52a4e4f14cd2d5474abb0"
      url "https://github.com/bethropolis/sift/releases/download/v#{version}/sift_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sift"
  desc "LLM-friendly codebase context picker"
  homepage "https://github.com/bethropolis/sift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sift"

  # No zap stanza required
end
