name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        run: brew bundle install --no-upgrade || true

      - name: Run brew audit (Formulae)
        run: |
          if ls Formula/*.rb 1> /dev/null 2>&1; then
            formula_names=$(for f in Formula/*.rb; do basename "$f" .rb; done)
            brew audit --strict --online $formula_names
          else
            echo "No Formulae found."
          fi

      - name: Run brew audit (Casks)
        if: runner.os == 'macOS'
        run: |
          if ls Casks/*.rb 1> /dev/null 2>&1; then
            cask_names=$(for c in Casks/*.rb; do basename "$c" .rb; done)
            brew audit --strict --online --cask --tap="${{ github.repository }}" $cask_names
          else
            echo "No Casks found."
          fi

      - name: Run brew style (Formulae)
        run: |
          if ls Formula/*.rb 1> /dev/null 2>&1; then
            brew style Formula/*.rb
          else
            echo "No Formulae found."
          fi

      - name: Run brew style (Casks)
        if: runner.os == 'macOS'
        run: |
          files="$(grep -L "generated by GoReleaser" Casks/*.rb 2>/dev/null || true)"
          if [ -n "$files" ]; then
            brew style --cask $files
          else
            echo "No non-generated casks to style."
          fi

      - name: Install and Test Formulae
        run: |
          if ls Formula/*.rb 1> /dev/null 2>&1; then
            for f in Formula/*.rb; do
              brew install "$f"
              brew test "$f"
            done
          else
            echo "No Formulae found."
          fi

      - name: Install and Dry Run Casks
        if: runner.os == 'macOS'
        run: |
          if ls Casks/*.rb 1> /dev/null 2>&1; then
            for c in Casks/*.rb; do
              cask_name=$(basename "$c" .rb)
              brew install --cask "${{ github.repository }}/$cask_name"
              echo "Running $cask_name --version"
              "$cask_name" --version
            done
          else
            echo "No Casks found."
          fi
